### ISSUE TITLE
Exemplo não mostra nada.

### ISSUE THREAD

**Issue by luizpaulo165** [LuisAraujo/API-Tabua-Mare#1]
E ae cara tudo tranquilo?! 
Gostei muito da iniciativa de criar essa API, realmente é muito útil.
Eu não sei se é noobisse, mas eu baixei o exemplo e no index ele não retorna nada. Não seria legal colocar um exemplo funcional?
Mais uma vez valeu pela iniciativa. =D

**Comment by LuisAraujo** [comment]
Olá Luiz, posso dar uma olhada e ver o que aconteceu! Abçs. Te retorno em breve.

**Comment by luizpaulo165** [comment]
Seria muito massa meu velho. Pois estou precisando exatamente disso para um projeto que estou fazendo. 
Valeu de verdade!

**Comment by LuisAraujo** [comment]
Olá Luiz, tudo ok?! Bem, espero que tenha resolvido a questão do seu projeto. Eu dei duas olhadas no código e tudo indica que é um erro no Jquery (porque ocorreu não sei). Desse modo, é preciso refazer a função "parse", mas estou sem tempo para isso. A ideia é refazê-la apenas com js, para evitar esse tipo de problema no futuro, pois ela funcionava perfeitamente. :+1:

**Comment by LuisAraujo** [comment]
@luizpaulo165 Problema resolvido!  Manda noticia sobre seu projeto.
