### ISSUE TITLE
A marinha removeu os dados do webservice

### ISSUE THREAD

**Issue by guischumacher** [LuisAraujo/API-Tabua-Mare#2]
Boa tarde Luis, tudo certo?

Antes de tudo parabéns pelo projeto! Acabei não usando exatamente seu projeto, mas me inspirou para desenvolver uma solução para wordpress usando a mesma fonte da marinha. O problema é que agora eles removeram e substituiram por um pdf com todo o ano para cada local =/
Você viu este erro já? Já conseguiu pensar em algo caso tenha visto? Caso não tenha visto e tiver projetos implementados com esta api, dá uma conferida pois provavelmente estão fora do ar!

Abraço e obrigado!

**Comment by LuisAraujo** [comment]
@guischumacher, tudo ok? Eu vi sim, algum dev me contactou querendo usá-la e vi este erro. Fui lá na página e vi que estava fora do ar, mas não achei esse pdf que vc fala, manda o link, talvez possamos obter dados dele.

**Comment by LuisAraujo** [comment]
@guischumacher encontrei o arquivo. É possível extrair dele sim.

**Comment by LuisAraujo** [comment]
Problema resolvido!

**Comment by guischumacher** [comment]
cara, você é demais hein! Parabéns!

**Comment by LuisAraujo** [comment]
@guischumacher falta apenas adicionar os links no arrLocations.js. Já existe um de exemplo, se for usar, você pode adicionar. Caso faça antes de mim, dá um pull request aqui, fico feliz. 

[]s
